spring:
  profiles:
    active: production
server:
  port: 8080
---
# DEVELOPMENT
spring:
  config:
    activate:
      on-profile: development
  main:
    log-startup-info: true
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # init src/main/resources schema.sql, data.sql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ewm-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
logging:
  level:
    org:
      springframework:
        web: TRACE # view HTTP-request
    ru:
      practicum:
        ewm: TRACE
stats-server:
  url: http://localhost:9090
---
# PRODUCTION
spring:
  config:
    activate:
      on-profile: production
  main:
    log-startup-info: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # init src/main/resources schema.sql, data.sql
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm-db
    driverClassName: org.postgresql.Driver
    username: sa
    password: password
stats-server:
  url: http://stats-server:9090
---
# TEST
spring:
  config:
    activate:
      on-profile: test
  main:
    log-startup-info: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # init src/main/resources schema.sql, data.sql  datasource:
    url: jdbc:h2:mem:ewm-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
stats-server:
  url: http://localhost:9090